[general]
apiEndpoint = "https://api-beta.backend.ai"
apiEndpointText = "Backend.AI Enterprise (Beta Branch)"
defaultSessionEnvironment = "index.docker.io/lablup/ngc-tensorflow"
connectionMode = "API"
signupSupport = false
allowSignout = false

[wsproxy]
#proxyBaseURL =
proxyURL = "https://beta-web.backend.ai/proxy/"
