[general]
#apiEndpoint =
#apiEndpointText =
#defaultSessionEnvironment =
siteDescription = "Console"
connectionMode = "SESSION" #connectionMode = API
allowChangeSigninMode = false # Allows user to change signin mode
signupSupport = false
debug = false

[wsproxy]
proxyURL = "https://wsproxy.onprem.backend.ai:9443/"
#proxyBaseURL = ""
disableCertCheck = false

[server]
consoleServerURL =

[plugin]
#login = "signup-cloud.js"
#sidebar = "report-cloud.js"
