[general]
apiEndpoint = "http://172.16.1.19:8081"
apiEndpointText = "Backend.AI Enterprise/On-premise (Demo-GTC2019)"
#defaultSessionEnvironment =
connectionMode = "API"

[wsproxy]
proxyURL = "http://172.16.1.19:5050/"
proxyBaseURL = "http://172.16.1.19"
proxyListenIP = "0.0.0.0"
