[general]
apiEndpoint = "https://lablup.onprem.backend.ai"
apiEndpointText = "Lablup Inc. Research Team / Backend.AI Enterprise"
defaultSessionEnvironment = "index.docker.io/lablup/ngc-tensorflow"
siteDescription = "DGX-2"
connectionMode = "API"
signupSupport = false

[wsproxy]
proxyURL = "https://wsproxy.onprem.backend.ai:9443/"
#proxyBaseURL =

[server]
consoleServerURL = "https://lablup.onprem.backend.ai"
