[general]
apiEndpoint = "http://192.168.1.101:8081"
apiEndpointText = "Backend.AI Enterprise/On-premise (GTC2019)"
defaultSessionEnvironment = "index.docker.io/lablup/ngc-tensorflow"
#siteDescription =
connectionMode = "API"

[wsproxy]
proxyBaseURL = "http://192.168.1.101"
proxyListenIP = "0.0.0.0"
proxyURL = "http://192.168.1.101:5050/"
