[general]
#apiEndpoint =
apiEndpointText = "Hana Cloudia"
defaultSessionEnvironment = "registry.hanacloudia.com/hana_nvidia/ngc-tensorflow"
siteDescription = "Hana Cloudia"
connectionMode = "SESSION"
allowChangeSigninMode = false
allowSignout = true
signupSupport = true
allowProjectResourceMonitor = true

[wsproxy]
proxyListenIP = "0.0.0.0"
disableCertCheck = true

[plugin]
#login = "test-plugin.js"
