[general]
apiEndpoint = "https://node01.kmu-bigdata.onpremise.backend.ai"
apiEndpointText = "KMU Bigdata / Backend.AI Enterprise"
defaultSessionEnvironment = "index.docker.io/lablup/ngc-tensorflow"
siteDescription = "Kookmin MBA"
connectionMode = "API"
signupSupport = false

[wsproxy]
#proxyURL = "https://web.kmu-bigdata.onpremise.backend.ai:8443/"
proxyURL = "https://wsproxy.onprem.backend.ai:8443/"
#proxyBaseURL =

[server]
consoleServerURL = ""
