[general]
#apiEndpoint =
#apiEndpointText =
#defaultSessionEnvironment =
siteDescription = "Console"
connectionMode = "SESSION"
allowChangeSigninMode = false
signupSupport = false
allowSignout = false
debug = false

[wsproxy]
proxyURL = "https://wsproxy.onprem.backend.ai:9443/"
#proxyBaseURL = ""

[server]
consoleServerURL =

[plugin]
#login = "signup-cloud.js"
#sidebar = "report-cloud.js"
