[general]
apiEndpoint = "https://node01.aihub.onprem.backend.ai"
apiEndpointText = "Backend.AI Enterprise"
defaultSessionEnvironment = "index.docker.io/lablup/python-tensorflow"
siteDescription = "AI Square"
connectionMode = "SESSION"
signupSupport = false
allowSignout = false
allowProjectResourceMonitor = false

[wsproxy]
proxyURL = "https://wsproxy.onprem.backend.ai:9443/"
#proxyBaseURL =

[server]
consoleServerURL = ""
