[general]
apiEndpoint = "https://node01.aihub.onprem.backend.ai"
apiEndpointText = "Backend.AI Enterprise"
defaultSessionEnvironment = "index.docker.io/lablup/python-tensorflow"
siteDescription = "AI Hub"
connectionMode = "API"

[wsproxy]
proxyURL = "https://wsproxy.onprem.backend.ai:8443/"
#proxyBaseURL =
