[general]
apiEndpoint = "https://tta-test.onprem.backend.ai:8081"
apiEndpointText = "TTA Test site / Backend.AI Enterprise"
defaultSessionEnvironment = "index.docker.io/lablup/ngc-tensorflow"
siteDescription = "on TTA"
connectionMode = "SESSION"
signupSupport = false

[wsproxy]
proxyURL = "https://wsproxy.onprem.backend.ai:9443/"

[server]
consoleServerURL = ""
